title: Yian(Ann) Wang # your name (or website title) here
logo: "/images/photo_new.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Becoming the best storyteller in spatial data science!
  <br><br>
  Master of Urban Spatial Analytics, University of Pennsylvania
  <br><br>
  <a href="https://www.linkedin.com/in/yian-wang-89a72917b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
